INSERT INTO STUDENT (ID, NAME)
VALUES (STU_SEQ.nextval, '桥本脆');
INSERT INTO STUDENT (ID, NAME)
VALUES (STU_SEQ.nextval, '李山泉');
INSERT INTO STUDENT (ID, NAME)
VALUES (STU_SEQ.nextval, '宫本嗨');
INSERT INTO STUDENT (ID, NAME)
VALUES (STU_SEQ.nextval, '诸葛狗蛋');
INSERT INTO STUDENT (ID, NAME)
VALUES (STU_SEQ.nextval, '东方XX');

INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '野外生存');
INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '下忍考试');
INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '魔法初级');
INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '书卷制作');
INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '机甲操作');
INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '战场救援');
INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '结界布置');
INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '聚宝盆初级测试');
INSERT INTO COURSE (ID, NAME)
VALUES (COURSE_SEQ.nextval, '钛人八千');
